{{ if .RuntimeSpec.IsOpenshift }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nic-configuration-operator
  namespace: {{ .RuntimeSpec.Namespace }}
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
{{ end }}
