# Copyright 2021 NVIDIA CORPORATION & AFFILIATES.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Custom Helm Chart values example to deploy Network Operator
# at NVIDIA DGX SYSTEMS.
# We don't need to deploy MOFED container.

nfd:
  enabled: true

# NicClusterPolicy CR values:
deployCR: true
ofedDriver:
  deploy: false

secondaryNetwork:
  deploy: true
  cniPlugins:
    deploy: true
    image: plugins
    repository: ghcr.io/k8snetworkplumbingwg
    version: v0.8.7-amd64
    imagePullSecrets: []
  multus:
    deploy: true
    image: multus-cni
    repository: ghcr.io/k8snetworkplumbingwg
    version: v3.8
    imagePullSecrets: []
  ipamPlugin:
    deploy: true
    image: whereabouts
    repository: ghcr.io/k8snetworkplumbingwg
    version: v0.5.4-amd64
    imagePullSecrets: []
