version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore:"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      kubernetes:
        patterns: [ "k8s.io/*" ]
    ignore:
      # Ignore k8s-operator-libs, controller-runtime, and Kubernetes major and minor updates. These should be done manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "github.com/NVIDIA/k8s-operator-libs"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "k8s.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    commit-message:
      prefix: "chore:"
