apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: network-operator
build:
  local:
    useBuildkit: true
  artifacts:
    - image: mellanox/network-operator
      runtimeType: go
      docker:
       buildArgs:
         ## Used for debugging. Disable inlining and optimizations in the go compiler. Passed to go build using `-gcflags`
         GCFLAGS: "all=-N -l"
         ARCH: "amd64"
       dockerfile: Dockerfile
manifests:
  ## Deploy the manager.
  kustomize:
    paths:
      - config/dev
portForward:
      - resourceType: deployment
        resourceName: nvidia-network-operator-controller-manager
        namespace: nvidia-network-operator
        port: 56268
        localPort: 8080
        address: 0.0.0.0
