- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: OFED_INIT_CONTAINER_IMAGE
    value: "nvcr.io/nvstaging/mellanox/network-operator-init-container:network-operator-v26.4.0-beta.3"
