- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: OFED_INIT_CONTAINER_IMAGE
    value: "nvcr.io/nvidia/mellanox/network-operator-init-container@sha256:922217cee504f080b2a76c51ec5d17baa562ffe2447bb1e370c01a6b26a7059f"
