resources:
- manager.yaml

commonLabels:
  control-plane: nvidia-network-operator-controller

generatorOptions:
  disableNameSuffixHash: true

kind: Kustomization
images:
- name: controller
  newName: mellanox/network-operator
