resources:
- manager.yaml

commonLabels:
  control-plane: nvidia-network-operator-controller

generatorOptions:
  disableNameSuffixHash: true

patches:
- path: init_container_image_name_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1

kind: Kustomization
images:
- name: controller
  newName: mellanox/network-operator
apiVersion: kustomize.config.k8s.io/v1beta1
