resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ea7becaa1cde597af6b87dc4e8377c68b64eb266f3c9d852ec756c83b961b253
  name: controller
  newName: nvcr.io/nvidia/cloud-native/network-operator
