# Adds namespace to all resources.
namespace: nvidia-network-operator

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: nvidia-network-operator-

bases:
- ../../crd
- ../../rbac
- ../../manager
- ../../webhook

patchesStrategicMerge:
- manager_webhook_patch.yaml
- webhookservicecainjection_patch.yaml
