apiVersion: v1
kind: Service
metadata:
  name: {{ include "maintenance-operator.name" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: maintenance-operator
    app.kubernetes.io/part-of: maintenance-operator
    control-plane: {{ .Release.Name }}-controller-manager
  {{- include "maintenance-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: {{ .Release.Name }}-controller-manager
  {{- include "maintenance-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}