apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maintenance-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: maintenance-operator
    app.kubernetes.io/part-of: maintenance-operator
  {{- include "maintenance-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}
