apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: webhook-server-cert
  creationTimestamp: null
  labels:
    control-plane: nvidia-network-operator-controller
  name: nvidia-network-operator-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: nvidia-network-operator-controller
status:
  loadBalancer: {}
