{{if eq .RuntimeSpec.OSName "rhcos"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-device-plugin
  namespace: {{ .RuntimeSpec.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-device-plugin
subjects:
- kind: ServiceAccount
  name: sriov-device-plugin
{{end}}
