{{ if .RuntimeSpec.IsOpenshift }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-operator-sriov-device-plugin
  namespace: {{ .RuntimeSpec.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-operator-sriov-device-plugin
subjects:
- kind: ServiceAccount
  name: network-operator-sriov-device-plugin
{{end}}
