---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mellanox-com-v1alpha1-hostdevicenetwork
  failurePolicy: Fail
  name: vhostdevicenetwork.kb.io
  rules:
  - apiGroups:
    - mellanox.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostdevicenetworks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mellanox-com-v1alpha1-nicclusterpolicy
  failurePolicy: Fail
  name: vnicclusterpolicy.kb.io
  rules:
  - apiGroups:
    - mellanox.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nicclusterpolicies
  sideEffects: None
