# 2023 NVIDIA CORPORATION & AFFILIATES
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nic-feature-discovery-ds
  namespace: {{ .RuntimeSpec.Namespace }}
  labels:
    tier: node
    app: nic-feature-discovery
    name: nic-feature-discovery
spec:
  selector:
    matchLabels:
      name: nic-feature-discovery
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: nic-feature-discovery
        name: nic-feature-discovery
    spec:
      terminationGracePeriodSeconds: 10
      {{ if .RuntimeSpec.IsOpenshift }}
      serviceAccountName: nic-feature-discovery
      {{- end }}
      tolerations:
        {{- if .Tolerations }}
          {{- .Tolerations | yaml | nindent 8 }}
        {{- end }}
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      {{- if .NodeAffinity }}
      affinity:
        nodeAffinity:
          {{- .NodeAffinity | yaml | nindent 10 }}
      {{- end }}
      {{- if .CrSpec.ImagePullSecrets }}
      imagePullSecrets:
      {{- range .CrSpec.ImagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: nic-feature-discovery
          image: {{ imagePath .CrSpec.Repository .CrSpec.Image .CrSpec.Version }}
          command: [ "/nic-feature-discovery" ]
          args:
            - --v=0
            - --logging-format=json
          {{- with .RuntimeSpec.ContainerResources }}
          {{- with index . "nic-feature-discovery" }}
          resources:
            {{- if .Requests }}
            requests:
              {{ .Requests | yaml | nindent 14}}
            {{- end }}
            {{- if .Limits }}
            limits:
              {{ .Limits | yaml | nindent 14}}
            {{- end }}
          {{- end }}
          {{- else }}
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "150Mi"
          {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: features-dir
              mountPath: /etc/kubernetes/node-feature-discovery/features.d
      volumes:
        - name: features-dir
          hostPath:
            path: /etc/kubernetes/node-feature-discovery/features.d
            type: DirectoryOrCreate
---
