apiVersion: v2
name: network-operator
version: 0.4.0
kubeVersion: '>= 1.17.0'
appVersion: v0.4.0
description: Nvidia Mellanox network operator
type: application
keywords:
  - gpu-direct
  - rdma
home: https://mellanox.github.io/network-operator
sources:
  - https://github.com/Mellanox/network-operator
dependencies:
- condition: nfd.enabled
  name: node-feature-discovery
  repository: ""
  version: 0.1.0
- condition: sriovNetworkOperator.enabled
  name: sriov-network-operator
  repository: ""
  version: 0.1.0

