apiVersion: v2
name: network-operator
version: 25.1.0-beta.3
kubeVersion: '>= 1.21.0'
appVersion: v25.1.0-beta.3
description: Nvidia network operator
type: application
keywords:
  - gpu-direct
  - rdma
home: https://mellanox.github.io/network-operator
sources:
  - https://github.com/Mellanox/network-operator
dependencies:
  - condition: nfd.enabled
    name: node-feature-discovery
    repository: http://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: 0.17.0
  - condition: sriovNetworkOperator.enabled
    name: sriov-network-operator
    repository: ''
    version: 0.1.0
  - condition: nicConfigurationOperator.enabled
    name: nic-configuration-operator-chart
    repository: ''
    version: 0.0.1
  - condition: maintenanceOperator.enabled
    name: maintenance-operator-chart
    repository: ''
    version: 0.0.1
