{{- if .Values.nfd.deployNodeFeatureRules }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nvidia-nics-rules
spec:
  rules:
    - name: "Nvidia NICs PCI"
      labels:
        "pci-15b3.present": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["15b3"]}
            class: {op: In, value: ["0200", "0207"]}
{{- end }}
