{{- if and .Values.deployCR .Values.rdmaSharedDevicePlugin.deploy  }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-dev-plugin-test"
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - image: mellanox/rping-test
      name: "{{ .Release.Name }}-dev-plugin-test"
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      resources:
        requests:
          rdma/{{ (index .Values.rdmaSharedDevicePlugin.resources 0).name }}: '1'
        limits:
          rdma/{{ (index .Values.rdmaSharedDevicePlugin.resources 0).name }}: '1'
      command:
        - sh
        - -c
        - |
          ls -l /dev/infiniband /sys/class/net /sys/class/infiniband
          if [[ "$(ls /dev/infiniband/ | wc -l)" -lt 4 ]]; then echo "Not all RDMA resouces mounted" >&2; exit 1; fi
{{- end }}
