{{ if .RuntimeSpec.IsOpenshift }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ofed-driver
  namespace: {{ .RuntimeSpec.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ofed-driver
subjects:
- kind: ServiceAccount
  name: ofed-driver
{{end}}
