# Copyright 2023 NVIDIA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}
    nvidia.com/ofed-driver: ""
  name: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}-ds
  namespace: {{ .RuntimeSpec.Namespace }}
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}
  template:
    metadata:
      labels:
        app: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}
        driver-pod: mofed-{{ .CrSpec.Version }}
        nvidia.com/ofed-driver: ""
    spec:
      priorityClassName: system-node-critical
      tolerations:
        {{- if .Tolerations }}
        {{- .Tolerations | yaml | nindent 8 }}
        {{- end }}
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      serviceAccountName: ofed-driver
      hostNetwork: true
      {{- if .CrSpec.ImagePullSecrets }}
      imagePullSecrets:
      {{- range .CrSpec.ImagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .RuntimeSpec.InitContainerConfig.InitContainerEnable  }}
      initContainers:
        - name: network-operator-init-container
          imagePullPolicy: IfNotPresent
          image: {{ .RuntimeSpec.InitContainerConfig.InitContainerImageName }}
          args:
            - --node-name
            - $(NODE_NAME)
            - --configmap-name
            - ofed-init-container-config
            - --configmap-namespace
            - {{ .RuntimeSpec.Namespace }}
            - --configmap-key
            - config.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      {{- end }}
      containers:
        - image: {{ .RuntimeSpec.MOFEDImageName }}
          imagePullPolicy: IfNotPresent
          name: mofed-container
          securityContext:
            privileged: true
            seLinuxOptions:
              level: "s0"
          env:
          {{- if .CrSpec.Env }}
          {{- range .CrSpec.Env }}
            {{ . | yaml | nindentPrefix 14 "- " }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: run-mlnx-ofed
              mountPath: /run/mellanox/drivers
              mountPropagation: Bidirectional
            - name: etc-network
              mountPath: /etc/network
            - name: host-etc
              mountPath: /host/etc
            - name: host-usr
              mountPath: /host/usr
            - name: host-udev
              mountPath: /host/lib/udev
            - name: host-lib-modules
              mountPath: /host/lib/modules
            {{- if.AdditionalVolumeMounts.VolumeMounts }}
            {{- range .AdditionalVolumeMounts.VolumeMounts }}
            - name: {{ .Name }}
              mountPath: {{ .MountPath }}
              subPath: {{ .SubPath }}
              readOnly: {{ .ReadOnly }}
            {{- end }}
            {{- end }}
          {{- range .CrSpec.ContainerResources }}
          {{- if eq .Name "mofed-container" }}
          resources:
            {{- if .Requests }}
            requests:
              {{ .Requests | yaml | nindent 14}}
            {{- end }}
            {{- if .Limits }}
            limits:
              {{ .Limits | yaml | nindent 14}}
            {{- end }}
          {{- end }}
          {{- end }}
          startupProbe:
            exec:
              command:
                [sh, -c, 'ls /.driver-ready']
            initialDelaySeconds: {{ .CrSpec.StartupProbe.InitialDelaySeconds }}
            failureThreshold: 60
            successThreshold: 1
            periodSeconds: {{ .CrSpec.StartupProbe.PeriodSeconds }}
          livenessProbe:
            exec:
              command:
                [sh, -c, 'lsmod | grep mlx5_core']
            initialDelaySeconds: {{ .CrSpec.LivenessProbe.InitialDelaySeconds }}
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: {{ .CrSpec.LivenessProbe.PeriodSeconds }}
          readinessProbe:
            exec:
              command:
                [sh, -c, 'lsmod | grep mlx5_core']
            initialDelaySeconds: {{ .CrSpec.ReadinessProbe.InitialDelaySeconds }}
            failureThreshold: 1
            periodSeconds: {{ .CrSpec.ReadinessProbe.PeriodSeconds }}
      # unloading OFED modules can take more time than default terminationGracePeriod (30 sec)
      terminationGracePeriodSeconds: {{ .CrSpec.TerminationGracePeriodSeconds }}
      volumes:
        - name: run-mlnx-ofed
          hostPath:
            path: /run/mellanox/drivers
        - name: etc-network
          hostPath:
            path: /etc/network
        - name: host-etc
          hostPath:
            path: /etc
        - name: host-usr
          hostPath:
            path: /usr
        - name: host-udev
          hostPath:
            path: /lib/udev
        - name: host-lib-modules
          hostPath:
            path: /lib/modules
        {{- range .AdditionalVolumeMounts.Volumes }}
        - name: {{ .Name }}
          configMap:
            name: {{ .Name }}
            items:
            {{- range .ConfigMap.Items }}
            {{ . | yaml | nindentPrefix 14 "- " }}
            {{- end }}
        {{- end }}
      nodeSelector:
        feature.node.kubernetes.io/pci-15b3.present: "true"
        feature.node.kubernetes.io/system-os_release.ID: {{ .RuntimeSpec.OSName }}
        feature.node.kubernetes.io/system-os_release.VERSION_ID: "{{ .RuntimeSpec.OSVer }}"
      {{- if .NodeAffinity }}
      affinity:
        nodeAffinity:
          {{- .NodeAffinity | yaml | nindent 10 }}
      {{- end }}
