// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedState) DeepCopyInto(out *AppliedState) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedState.
func (in *AppliedState) DeepCopy() *AppliedState {
	if in == nil {
		return nil
	}
	out := new(AppliedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginSpec) DeepCopyInto(out *DevicePluginSpec) {
	*out = *in
	out.ImageSpec = in.ImageSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginSpec.
func (in *DevicePluginSpec) DeepCopy() *DevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultusSpec) DeepCopyInto(out *MultusSpec) {
	*out = *in
	out.ImageSpec = in.ImageSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultusSpec.
func (in *MultusSpec) DeepCopy() *MultusSpec {
	if in == nil {
		return nil
	}
	out := new(MultusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVPeerDriverSpec) DeepCopyInto(out *NVPeerDriverSpec) {
	*out = *in
	out.ImageSpec = in.ImageSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVPeerDriverSpec.
func (in *NVPeerDriverSpec) DeepCopy() *NVPeerDriverSpec {
	if in == nil {
		return nil
	}
	out := new(NVPeerDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicClusterPolicy) DeepCopyInto(out *NicClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicClusterPolicy.
func (in *NicClusterPolicy) DeepCopy() *NicClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(NicClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NicClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicClusterPolicyList) DeepCopyInto(out *NicClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NicClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicClusterPolicyList.
func (in *NicClusterPolicyList) DeepCopy() *NicClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(NicClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NicClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicClusterPolicySpec) DeepCopyInto(out *NicClusterPolicySpec) {
	*out = *in
	if in.OFEDDriver != nil {
		in, out := &in.OFEDDriver, &out.OFEDDriver
		*out = new(OFEDDriverSpec)
		**out = **in
	}
	if in.NVPeerDriver != nil {
		in, out := &in.NVPeerDriver, &out.NVPeerDriver
		*out = new(NVPeerDriverSpec)
		**out = **in
	}
	if in.DevicePlugin != nil {
		in, out := &in.DevicePlugin, &out.DevicePlugin
		*out = new(DevicePluginSpec)
		**out = **in
	}
	if in.SecondaryNetwork != nil {
		in, out := &in.SecondaryNetwork, &out.SecondaryNetwork
		*out = new(SecondaryNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicClusterPolicySpec.
func (in *NicClusterPolicySpec) DeepCopy() *NicClusterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NicClusterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicClusterPolicyStatus) DeepCopyInto(out *NicClusterPolicyStatus) {
	*out = *in
	if in.AppliedStates != nil {
		in, out := &in.AppliedStates, &out.AppliedStates
		*out = make([]AppliedState, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicClusterPolicyStatus.
func (in *NicClusterPolicyStatus) DeepCopy() *NicClusterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NicClusterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OFEDDriverSpec) DeepCopyInto(out *OFEDDriverSpec) {
	*out = *in
	out.ImageSpec = in.ImageSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OFEDDriverSpec.
func (in *OFEDDriverSpec) DeepCopy() *OFEDDriverSpec {
	if in == nil {
		return nil
	}
	out := new(OFEDDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryNetworkSpec) DeepCopyInto(out *SecondaryNetworkSpec) {
	*out = *in
	if in.Multus != nil {
		in, out := &in.Multus, &out.Multus
		*out = new(MultusSpec)
		**out = **in
	}
	if in.CniPlugins != nil {
		in, out := &in.CniPlugins, &out.CniPlugins
		*out = new(ImageSpec)
		**out = **in
	}
	if in.IpamPlugin != nil {
		in, out := &in.IpamPlugin, &out.IpamPlugin
		*out = new(ImageSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryNetworkSpec.
func (in *SecondaryNetworkSpec) DeepCopy() *SecondaryNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(SecondaryNetworkSpec)
	in.DeepCopyInto(out)
	return out
}
