# permissions for end users to view hostdevicenetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostdevicenetwork-viewer-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - hostdevicenetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - hostdevicenetworks/status
  verbs:
  - get
