apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: rdma/hca_shared_devices_a
  name: rdma-net-hostdev
  namespace: default
spec:
  # Configuration below assumes 'ens2f0' as master device for host-device CNI,
  # replace with (RDMA capable) netdevice of your choice.
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "rdma-net-hostdev",
        "plugins": [
            {
                "type": "host-device",
                "master": "ens2f0"
            }
        ]
    }
