apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: {{ .RuntimeSpec.Namespace }}
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      securityContext:
        privileged: true
      {{- if .NodeAffinity }}
      affinity:
        nodeAffinity:
          {{- .NodeAffinity | yaml | nindent 10 }}
      {{- end }}
      serviceAccountName: multus
      {{- if .CrSpec.ImagePullSecrets }}
      imagePullSecrets:
      {{- range .CrSpec.ImagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      tolerations:
        {{- if .Tolerations }}
        {{- .Tolerations | yaml | nindent 8 }}
        {{- end }}
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: install-multus-binary
          image: {{ imagePath .CrSpec.Repository .CrSpec.Image .CrSpec.Version }}
          command: ["/install_multus"]
          args:
            - "--type"
            {{- if eq .CrSpec.DeploymentType "thick" }}
            - "thick"
            {{- else }}
            - "thin"
            {{- end }}
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
      containers:
        - name: kube-multus
          image: {{ imagePath .CrSpec.Repository .CrSpec.Image .CrSpec.Version }}
          {{- if eq .CrSpec.DeploymentType "thick" }}
          command: ["/usr/src/multus-cni/bin/multus-daemon"]
          args:
            - "--config=/etc/cni/net.d/multus.d/daemon-config.json"
          {{- else }}
          command: ["/thin_entrypoint"]
          args:
            - "--multus-conf-file=auto"
            - "--multus-autoconfig-dir=/host/etc/cni/net.d"
            - "--cni-conf-dir=/host/etc/cni/net.d"
            - "--cleanup-config-on-exit"
            - "--skip-config-watch"
            - "--cni-bin-dir=/host/opt/cni/bin"
            - "--multus-kubeconfig-file-host={{ .RuntimeSpec.CniNetworkDirectory }}/multus.d/multus.kubeconfig"
          {{- end }}
          {{- with .RuntimeSpec.ContainerResources }}
          {{- with index . "kube-multus" }}
          resources:
            {{- if .Requests }}
            requests:
              {{ .Requests | yaml | nindent 14}}
            {{- end }}
            {{- if .Limits }}
            limits:
              {{ .Limits | yaml | nindent 14}}
            {{- end }}
          {{- end }}
          {{- else }}
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          {{- end }}
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePolicy: FallbackToLogsOnError
          {{- if eq .CrSpec.DeploymentType "thick" }}
          env:
            - name: MULTUS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- end }}
          volumeMounts:
          {{- if eq .CrSpec.DeploymentType "thick" }}
            - name: cni
              mountPath: /host/etc/cni/net.d
            - name: cnibin
              mountPath: {{ .RuntimeSpec.CniBinDirectory }}
            - name: host-run
              mountPath: /host/run
            - name: host-var-lib-cni-multus
              mountPath: /var/lib/cni/multus
            - name: host-var-lib-kubelet
              mountPath: /var/lib/kubelet
              mountPropagation: HostToContainer
            - name: host-run-k8s-cni-cncf-io
              mountPath: /run/k8s.cni.cncf.io
            - name: host-run-netns
              mountPath: /run/netns
              mountPropagation: HostToContainer
            - name: multus-cni-config
              mountPath: /etc/cni/net.d/multus.d
              readOnly: true
            - name: hostroot
              mountPath: /hostroot
              mountPropagation: HostToContainer
          {{- else }}
            - name: cninetwork
              mountPath: /host/etc/cni/net.d
            - name: cnibin
              mountPath: /host/opt/cni/bin
          {{- end }}
      volumes:
      {{- if eq .CrSpec.DeploymentType "thick" }}
        - name: cni
          hostPath:
            path: {{ .RuntimeSpec.CniNetworkDirectory }}
        - name: cnibin
          hostPath:
            path: {{ .RuntimeSpec.CniBinDirectory }}
        - name: hostroot
          hostPath:
            path: /
        - name: multus-cni-config
          configMap:
            name: multus-daemon-config
            items:
            - key: daemon-config.json
              path: daemon-config.json
        - name: host-run
          hostPath:
            path: /run
        - name: host-var-lib-cni-multus
          hostPath:
            path: /var/lib/cni/multus
        - name: host-var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: host-run-k8s-cni-cncf-io
          hostPath:
            path: /run/k8s.cni.cncf.io
        - name: host-run-netns
          hostPath:
            path: /run/netns
      {{- else }}
        - name: cninetwork
          hostPath:
            path: {{ .RuntimeSpec.CniNetworkDirectory }}
        - name: cnibin
          hostPath:
            path: {{ .RuntimeSpec.CniBinDirectory }}
      {{- end }}
