/*
Copyright 2022 NVIDIA CORPORATION & AFFILIATES
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by mockery v1.0.0. DO NOT EDIT.
//nolint
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import v1 "k8s.io/api/core/v1"

// PodDeleteManager is an autogenerated mock type for the PodDeleteManager type
type PodDeleteManager struct {
	mock.Mock
}

// SchedulePodsRestart provides a mock function with given fields: _a0, _a1
func (_m *PodDeleteManager) SchedulePodsRestart(_a0 context.Context, _a1 []*v1.Pod) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*v1.Pod) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
