/*
Copyright 2022 NVIDIA CORPORATION & AFFILIATES
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by mockery v1.0.0. DO NOT EDIT.
//nolint
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import v1 "k8s.io/api/core/v1"

// UncordonManager is an autogenerated mock type for the UncordonManager type
type UncordonManager struct {
	mock.Mock
}

// CordonOrUncordonNode provides a mock function with given fields: ctx, node, desired
func (_m *UncordonManager) CordonOrUncordonNode(ctx context.Context, node *v1.Node, desired bool) error {
	ret := _m.Called(ctx, node, desired)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Node, bool) error); ok {
		r0 = rf(ctx, node, desired)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
