apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spectrum-x-flowcontroller
  namespace: {{ .RuntimeSpec.Namespace }}
  labels:
    control-plane: spectrum-x-flowcontroller
    app.kubernetes.io/name: spectrum-x-operator
spec:
  selector:
    matchLabels:
      control-plane: spectrum-x-flowcontroller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: spectrum-x-flowcontroller
      labels:
        control-plane: spectrum-x-flowcontroller
    spec:
      tolerations:
        {{- if .Tolerations }}
        {{- .Tolerations | yaml | nindent 8 }}
        {{- end }}
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      securityContext:
        runAsNonRoot: false
      hostNetwork: true
      {{- if .CrSpec.ImagePullSecrets }}
      imagePullSecrets:
      {{- range .CrSpec.ImagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - command:
            - /flowcontroller
          args:
            - --cm-namespace={{ .RuntimeSpec.Namespace }}
            {{- if and .CrSpec.SpectrumXConfig .CrSpec.SpectrumXConfig.Name }}
            - --cm-name={{ .CrSpec.SpectrumXConfig.Name }}
            {{- end }}
            - --metrics-bind-address=:8082
            - --health-probe-bind-address=:8084
          image: {{ imagePath .CrSpec.Repository .CrSpec.Image .CrSpec.Version }}
          name: spectrum-x-flowcontroller
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              drop:
                - "ALL"
          volumeMounts:
            - name: proc
              mountPath: /proc
            - name: sys
              mountPath: /sys
            - name: ovs
              mountPath: /var/run/openvswitch/
            - name: ovs-systemd-config
              mountPath: /etc/default/openvswitch-switch
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .RuntimeSpec.ContainerResources }}
          {{- with index . "spectrum-x-flowcontroller" }}
          resources:
            {{- if .Requests }}
            requests:
              {{ .Requests | yaml | nindent 14 }}
            {{- end }}
            {{- if .Limits }}
            limits:
              {{ .Limits | yaml | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: ovs
          hostPath:
            path: /var/run/openvswitch
        - name: ovs-systemd-config
          hostPath:
            path: /etc/default/openvswitch-switch
      serviceAccountName: spectrum-x-operator
      {{- if .NodeAffinity }}
      affinity:
        nodeAffinity:
          {{- .NodeAffinity | yaml | nindent 10 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
