{{ if .RuntimeSpec.IsOpenshift }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spectrum-x-operator
  namespace: {{ .RuntimeSpec.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spectrum-x-operator
subjects:
  - kind: ServiceAccount
    name: spectrum-x-operator
    namespace: {{ .RuntimeSpec.Namespace }}
{{ end }}
