apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ofed-driver
  namespace: mlnx-network-operator
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
