apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.HostDeviceNetworkName}}
  namespace: {{.CrSpec.NetworkNamespace}}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{.ResourceName}}
spec:
  config:
    '{{.CNISpec | json}}'
