apiVersion: v1
kind: ConfigMap
metadata:
  name: nic-configuration-operator-config
data:
  serviceAccountName: "{{ include "nic-configuration-operator.serviceAccountName" . }}"
  configDaemonImage: "{{ .Values.configDaemon.image.repository }}/{{ .Values.configDaemon.image.name }}:{{ .Values.configDaemon.image.tag | default .Chart.AppVersion }}"
  {{- if .Values.imagePullSecrets}}
  imagePullSecrets: {{ join "," .Values.imagePullSecrets }}
  {{- end}}
  {{- if .Values.configDaemon.nodeSelector}}
  nodeSelector: {{ .Values.configDaemon.nodeSelector | toJson | quote }}
  {{- end}}
  {{- if .Values.configDaemon.resources}}
  resources: {{ .Values.configDaemon.resources | toJson | quote }}
  {{- end}}
  {{- if .Values.logLevel}}
  logLevel: {{ .Values.logLevel }}
  {{- end}}