apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nic-configuration-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nic-configuration-operator
    app.kubernetes.io/part-of: nic-configuration-operator
    {{- include "nic-configuration-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}
