name: "Build"
on: [push, pull_request]

jobs:
  lint-code:
    name: golangci-lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28.3
          args: --timeout 10m
  lint-docker:
    name: hadolint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
  lint-helm:
    name: helm lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./deployment/network-operator/
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'
      - name: checkout
        uses: actions/checkout@v2
      - name:  run tests
        run: make test
