name: Conventional Commit PR message check

on:
  pull_request:
    branches:
    - "master"
    - "v[0-9]+.[0-9]+.x"
    types: [opened, edited, synchronize]

jobs:
  check-for-cc:
    runs-on: ubuntu-24.04
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
        with:
          pr-body-regex: '.*'
