name: Documentation CI - call downstream workflow

on:
  push:
    tags:
    - "v*"
    paths:
    - deployment/**/values.yaml
    - api/**    

  pull_request:
    types:
    - opened
    - synchronize
    - edited
    paths:
    - deployment/**/values.yaml
    - api/**

jobs:
  trigger_downstream_workflow:
    uses: maze88/sandbox/.github/workflows/test.yaml@master
    secrets:
      gh_docs_token: ${{ secrets.GH_DOCS_TOKEN }}