name: Documentation CI - call downstream workflow

on:
  push:
    tags:
    - "v*"

jobs:
  trigger_downstream_workflow:
    uses: Mellanox/network-operator-docs/.github/workflows/docs-ci.yaml@main
    with:
      token: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      git_tag: ${{ github.ref_name }}
    secrets: inherit
