on:
  issues:
    types:
      - opened

jobs:
  update-network-operator-version:
    if: startsWith(github.event.issue.title, 'Release v')
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
      - uses: actions/checkout@v4
      - id: set-version
        run: |
          # full release version, i.e. v25.4.0-rc.1
          APP_VERSION=$(echo $ISSUE_TITLE | awk '{ print $2 }')
          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "APP_VERSION=${APP_VERSION}" | tee -a $GITHUB_ENV

          # major.minor version with v prefix and x suffix, i.e. v25.4.x
          V_MAJOR_MINOR_X=$(echo $APP_VERSION | grep -Eo '^v[0-9]+\.[0-9]+').x
          echo "V_MAJOR_MINOR_X=${V_MAJOR_MINOR_X}" | tee -a $GITHUB_ENV

          # major.minor version without v prefix and with x suffix, i.e. 25.4.x
          MAJOR_MINOR_X=$(echo ${V_MAJOR_MINOR_X#v})
          echo "major_minor_x=${MAJOR_MINOR_X}" >> $GITHUB_OUTPUT
      - run: |
          echo "CHART_VERSION=$(echo ${APP_VERSION#v})" | tee -a $GITHUB_ENV
      - name: Determine base branch
        run: |
          if echo $APP_VERSION | grep -q beta; then
            base_branch=master
          else
            base_branch=$V_MAJOR_MINOR_X
          fi
          echo BASE_BRANCH=$base_branch | tee -a $GITHUB_ENV
      - name: Verify release branch exists if "rc" version
        run: |
          if echo $APP_VERSION | grep -q 'rc'; then
            git fetch origin
            if ! git ls-remote --heads origin $BASE_BRANCH | grep -q "$BASE_BRANCH"; then
              git config user.name  nvidia-ci-cd
              git config user.email svc-cloud-orch-gh@nvidia.com
              git checkout -b $BASE_BRANCH
              git push -u origin $BASE_BRANCH
            fi
          fi
      - run: |
          git config user.name  nvidia-ci-cd
          git config user.email svc-cloud-orch-gh@nvidia.com
          git fetch origin $BASE_BRANCH
          git checkout -b cicd/update-network-operator-to-$APP_VERSION origin/$BASE_BRANCH
          yq -i '.NetworkOperator.version = "${{ env.APP_VERSION }}"' hack/release.yaml
          yq -i '.version = "${{ env.CHART_VERSION }}"'               deployment/network-operator/Chart.yaml
          yq -i '.appVersion = "${{ env.APP_VERSION }}"'              deployment/network-operator/Chart.yaml
          make release-build

          if ! git diff --color --unified=0 --exit-code; then
            git add deployment/network-operator/
            git add hack/release.yaml
            git commit -sam "cicd: update Network Operator to $APP_VERSION in chart values"
            git push -u origin cicd/update-network-operator-to-$APP_VERSION
            gh pr create \
              --repo ${{ github.repository_owner }}/network-operator \
              --base $BASE_BRANCH \
              --head $(git branch --show-current) \
              --title "cicd: update Network Operator to $APP_VERSION in chart values" \
              --body "Created by the [*${{ github.job }}* job](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          fi
    outputs:
      app_version: ${{ steps.set-version.outputs.app_version }}
      major_minor_x: ${{ steps.set-version.outputs.major_minor_x }}

  get-managed-components:
    needs: update-network-operator-version
    runs-on: ubuntu-24.04
    outputs:
      managed_components: ${{ steps.set-components.outputs.managed_components }}
    steps:
      - uses: actions/checkout@v4
      - id: set-components
        run: |
          # Extract the sourceRepository field from each component
          # This will create a JSON array of the repository names
          components=$(yq -o=json 'to_entries | map(select(.value.sourceRepository != null) | .value.sourceRepository)' hack/release.yaml | jq -c .)
          echo $components
          echo "managed_components=$(echo $components)" >> $GITHUB_OUTPUT

  update-component-versions:
    runs-on: ubuntu-24.04
    needs: [get-managed-components, update-network-operator-version]
    strategy:
      matrix:
        component: ${{ fromJson(needs.get-managed-components.outputs.managed_components) }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      APP_VERSION: ${{ needs.update-network-operator-version.outputs.app_version }}
      MAJOR_MINOR_X: ${{ needs.update-network-operator-version.outputs.major_minor_x }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
          repository: ${{ github.repository_owner }}/${{ matrix.component }}
          path: ${{ matrix.component }}
          fetch-depth: 0
      - name: Create tag to trigger PR that update image tags in network-operator values
        run: |
          cd ${{ matrix.component }}
          git config user.name  nvidia-ci-cd
          git config user.email svc-cloud-orch-gh@nvidia.com
          git fetch origin

          RELEASE_BRANCH=network-operator-${MAJOR_MINOR_X}

          echo "Checking if the release branch exists"
          if git ls-remote --heads origin $RELEASE_BRANCH | grep -q "$RELEASE_BRANCH"; then
            echo "Release branch exists, using it"
            git checkout -b $APP_VERSION origin/$RELEASE_BRANCH
          else
            echo "Release branch doesn't exist, creating it"
            echo "Branch $RELEASE_BRANCH does not exist for ${{ matrix.component }}, creating it from default branch"

            git checkout -b $RELEASE_BRANCH
            git push -u origin $RELEASE_BRANCH

            echo "Creating the version branch from the new release branch"
            git checkout -b $APP_VERSION
          fi

          echo "Creating and pushing the tag"
          git tag network-operator-$APP_VERSION
          git push origin --tags
